version: "3"

services:
  app:
    container_name: ahmed-container
    user: "${UID}:${GID}"
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src/app:/src/app
    command: >
      sh -c "/rapid_env/bin/python manage.py wait_for_db && 
            /rapid_env/bin/python manage.py migrate &&
            /rapid_env/bin/python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=ahmed.siddiqui
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=app
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=ahmed.siddiqui
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=app
    
  # nginx:

  #   # Instead of referencing image: nginx:mainline-alpine here, use build to
  #   # reference the current directory (.), which will look for a dockerfile
  #   # by default
  #   build: ./etc/
  #   # The external directory location to map to an internal location
  #   volumes:
  #     - ./src/app:/src/app
  #   # The external port mapping to internal port mapping
  #   ports:
  #     - "81:81"

