version: "3"

services:
  app:
    user: "${UID}:${GID}"
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/src/app
    command: >
      sh -c "python manage.py runserver"

